[package]
name = "smtp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
smtp = { path = "../smtp" }
miette = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
