[package]
name = "smtp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
smtp = { path = "../smtp" }
miette = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
mail-parser = "0.9.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.128"
camino = "1.1.9"
ulid = "1.1.3"
config = { version = "0.14.0", default-features = false, features = [
    "async",
    "toml",
] }
async-channel = "2.3.1"
