[workspace]
members = ["smtp-server", "smtp"]
resolver = "2"

[workspace.dependencies]
miette = { version = "7.2.0", features = ["fancy"] }
thiserror = "1.0.64"
tokio = { version = "1.40.0", features = [
    "net",
    "io-util",
    "rt-multi-thread",
    "macros",
    "fs",
    "io-std",
] }
