[package]
name = "smtp"
version = "0.12.2"
edition = "2021"

[features]
default = ["tokio"]
tokio = ["dep:tokio", "dep:tokio-rustls"]
compio = ["dep:compio"]

[dependencies]
base64 = "0.22.1"
miette = { workspace = true }
nom = "8.0.0"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time"], optional = true }
async-trait = { workspace = true }
tokio-rustls = { version = "0.26.1", optional = true }
compio = { version = "0.19.2", features = [
    "io",
    "io-compat",
    "net",
    "time",
    "rustls",
    "bytes",
], optional = true }
bytes = "1.10.0"
memchr = "2.7.4"

[dev-dependencies]
tokio = { workspace = true, features = ["time", "macros", "rt", "io-util"] }
